name: CI/CD Devops

on:
 push:
  branches: [ main ]

jobs:
 build:
   runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/login-actions@v3

   - name: Login DockerHub
     uses: docker/login-action@v2
     with:
       username: ${{ secrets.DOCKER_USER }}
       password: ${{ secrets.Docker_PASS }}

   - name: Build Docker image
     run: docker build -t santrhay/devops-app:latest .


  - name: Push Docker image
    run: docker push santrhay/devops-app
